fail_fast: false
exclude: ^.*\b(migrations)\b.*$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements

- repo: local

  hooks:
    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [python]
      args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]

    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--line-length=120, --target-version=py312]

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]